app/project/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import ValidationError, DataRequired
from app.models import Project


def has_space(string, msg):
    if " " in string:
        raise ValidationError(msg)


class ProjectForm(FlaskForm):
    name = StringField('', validators=[DataRequired()])
    submit = SubmitField('Add project')

    def validate_name(self, name):
        project = Project.query.filter_by(name=name.data.lower()).first()
        if project is not None:
            raise ValidationError("This project already exists")
        has_space(name.data, "Please use \"_\" instead of space in project name")


class EditProjectForm(FlaskForm):
    name = StringField('New name', validators=[DataRequired()])
    submit = SubmitField('Edit project name')

    def __init__(self, old_name, *args, **kwargs):
        super(EditProjectForm, self).__init__(*args, **kwargs)
        self.old_name = old_name

    def validate_name(self, name):
        if name.data.lower() != self.old_name.lower():
            project = Project.query.filter_by(name=name.data.lower()).first()
            if project is not None:
                raise ValidationError("Use a different name")
            has_space(name.data, "Please use \"_\" instead of space in project name")
        else:
            raise ValidationError("The project is already named {}".format(name.data.upper()))

app/project/__init__.py
from flask import Blueprint


bp = Blueprint('project', __name__)


from app.project import routes

app/project/routes.py
import threading
from flask import render_template, redirect, url_for, flash, request, jsonify
from app import db, d as Device
from app.project import bp, _project
from app.project._project import folder
from app.device import device
from app.models import Project, Apk
from app.configuration import install_apks
from app.project.forms import ProjectForm, EditProjectForm


@bp.route('/projects', methods=["GET", "POST"])
def projects():
    form = ProjectForm()
    projects = Project.query.all()
    if form.validate_on_submit():
        path = folder().create_folder(form.name.data.lower())
        project = Project(name=form.name.data.lower(), path=path)
        db.session.add(project)
        db.session.commit()
        flash("{} has been created".format(form.name.data.upper()))
        return redirect(url_for("project.projects"))
    return render_template('project/projects.html', title='All projects', form=form, projects=projects)


@bp.route('/<id>', methods=["GET", "POST"])
def project(id):
    project = Project.query.filter_by(id=id).first()
    connected = device.get_devices()
    all_apks = Apk.query.all()
    not_linked_apks = project.get_apks_not_link()
    linked_apks = project.apks
    wallpapers = _project.get_wallpaper(project.name.lower())

    # if request.method == 'POST':
    #     f = request.form.get("form_id", "")
    #     if f == "applications":
    #         _project.add_apks(project=project, request=request)
    #     if f == "wallpaper":
    #         _project.upload_wallpaper(request=request, project=project.name.lower())
    #     return redirect(url_for("project.project", id=id))

    return render_template('project/project.html', title=project.name.upper(), project=project,
                           connected=connected, apks=linked_apks, not_linked_apks=not_linked_apks,
                           all_apks=all_apks, wallpapers=wallpapers)


@bp.route('/upload/<id>', methods=["POST"])
def upload(id):
    project = Project.query.filter_by(id=id).first()
    filename = _project.upload_wallpaper(request=request, project=project.name.lower())
    path = []
    for f in filename:
        path.append("projects/" + project.name.lower() + "/wallpaper/" + f)

    return jsonify(path)


@bp.route('/add_apk/<id>', methods=["POST"])
def add_apk(id):
    project = Project.query.filter_by(id=id).first()
    apks = _project.add_apks(project=project, request=request)
    return jsonify(apks)


@bp.route('/delete/<id>', methods=["GET", "POST"])
def delete(id):
    project = Project.query.filter_by(id=id).first()
    if project.has_devices():
        flash("{} has devices".format(project.name))
        return redirect(url_for("project.projects"))
    db.session.delete(project)
    db.session.commit()
    folder().remove_project(project.name.lower())
    flash("{} has been deleted".format(project.name.upper()))
    return redirect(url_for("project.projects"))


@bp.route('/delete_apk/<apk_id>/<project_id>', methods=["GET", "POST"])
def delete_apk(apk_id, project_id):
    _project.delete_apk(apk_id=apk_id, project_id=project_id)
    return redirect(url_for("project.project", id=project_id))


@bp.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    project = Project.query.filter_by(id=id).first()
    form = EditProjectForm(project.name)
    if form.validate_on_submit():
        old_name = project.name
        project.name = form.name.data.lower()
        new_path = folder().rename_project(old_name.lower(), form.name.data.lower())
        project.path = new_path
        db.session.commit()
        flash("The project {} has been changed to {}".format(old_name.upper(), form.name.data.upper()))
        return jsonify(status='ok')
    return render_template('project/edit/edit.html', form=form, project=project)


@bp.route('/configure/<id>', methods=['GET', 'POST'])
def configure(id):
    connected = device.get_devices()
    project = Project.query.filter_by(id=id).first()
    if connected:
        # p = None
        # for d in connected:
        #     p = Process(target=conf(project=project, _device=d))
        # p.start()
        for d in connected:
            sn = d.adb_sn
            Device.set_serial(sn)
            print("configure {}".format(sn))
            threading.Thread(target=install_apks, args=(Device, project.apks,)).start()
            #conf(project=project, sn=sn)

    return redirect(url_for("project.project", id=id))

app/templates/project/project.html
{% extends "base.html" %}

{% block app_content %}
    <div class="page-header">
		<h1>{{ title }}</h1>
	</div>
    <div class="page-header">
        <h1><small>Configuration</small></h1>
    </div>
    <!-- APK -->
    <div class="panel panel-primary">
        <div class="panel-body">
            <h3 class="text-on-pannel text-primary"><strong class="text-uppercase"> applications </strong></h3>
            {% if all_apks %}
                {% if not_linked_apks %}
                <form action="" method="POST" id="link_apks" name="link_apks">
                    <fieldset>
                        <input value="applications" type="hidden" name="form_id">
                        <input value="{{ project.id }}" type="hidden" name="project_id">
                        <div class="form-group">
                            <label for="SelectApk">Select Applications</label>
                            <select multiple class="selectpicker form-control" name="apk" id="SelectApk">
                                {% for apk in not_linked_apks %}
                                <option data-subtext="{{ apk.filename }}">{{ apk.package_name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <button id="submit" type="submit" class="btn btn-primary">
                                <span class="glyphicon glyphicon-refresh glyphicon-refresh-animate hide"></span>
                                Submit
                            </button>
                        </div>
                    </fieldset>
                </form>
                {% else %}
                <div>
                    <p class="text-muted">All applications are linked to {{ project.name }}</p>
                </div>
                {% endif %}
                {% include 'apk/_linked_apk.html' %}
            {% else %}
                <a href="{{ url_for('apk.applications') }}">Add applications</a>
            {% endif %}
        </div>
    </div>
    <!-- END APK -->
    <!-- WALLPAPER -->
    <div class="panel panel-primary">
        <div class="panel-body">
            <h3 class="text-on-pannel text-primary"><strong class="text-uppercase"> wallpaper </strong></h3>
            <form action="" method="POST" enctype="multipart/form-data" id="wallpaper" name="wallpaper">
                <fieldset>
                    <input value = "wallpaper" type="hidden" name="form_id">
                    <input value="{{ project.id }}" type="hidden" name="project_id">
                    <div class="form-group">
                        <div class="input-group input-wallpaper">
                            <span class="input-group-btn">
                                <button class="btn btn-default btn-danger btn-choose" type="button">
                                    Choose
                                </button>
                            </span>
                            <input type="text" class="form-control" placeholder="Choose wallpaper" />
                            <span class="input-group-btn">
                                <button class="btn btn-warning btn-reset" type="button">
                                    Reset
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </fieldset>
            </form>
            {% include 'progress_bar.html' %}
            {% if wallpapers %}
            <div id="wall_gallery" class="row">
                {% for wallpaper in wallpapers %}
                <div class="col-xs-3">
                    <a href="{{ url_for('static', filename=wallpaper) }}" class="thumbnail" data-fancybox="images">
                        <img src="{{ url_for('static', filename=wallpaper) }}" />
                    </a>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div>
                <p class="text-muted">No wallpapers loaded</p>
            </div>
            {% endif %}
        </div>
    </div>
    <!-- END WALLPAPER -->
    <!-- SETTINGS -->
    <div class="panel panel-primary">
        <div class="panel-body">
            <h3 class="text-on-pannel text-primary"><strong class="text-uppercase"> settings </strong></h3>
        </div>
    </div>
    <!-- END SETTINGS -->
    {% if connected %}
        <a href="{{ url_for('project.configure', id=project.id) }}">configure</a>
    {% else %}
        <div>
            <p class="text-muted">connect devices to start the configuration</p>
        </div>
    {% endif %}


    <div class="page-header">
        <h1><small>Device Plugged in</small></h1>
    </div>
    {% include 'device/_connected.html' %}
{% endblock %}

app/templates/project/projects.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <div id="editProjectDialog" class="modal fade" tabindex=-1 role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            </div>
        </div>
    </div>
    {# ADD PROJECT #}
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <div class="page-header">
		<h1>Projects</h1>
	</div>
    {# DISPLAY ALL Projects #}
    {% if projects %}
    <table id="project" class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Project name</th>
                <th scope="col">Configured Devices</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
            <tr>
                <th scope="row">{{ project.id }}</th>
                <td><a href="{{ url_for('project.project', id=project.id) }}">{{ project.name.upper() }}</a></td>
                <td>{{ project.devices.count() }}</td>
                <td><a href="javascript:edit({{ project.id }})"><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                    <a href="{{ url_for('project.delete', id=project.id) }}">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <div>
        <p class="text-muted">No projects</p>
    </div>
    {% endif %}
{% endblock %}